pipeline{
    agent none
    environment{
        TEST = "This is a test variable"
        TEST1 = "This is a test1 variable"
    }
    parameters{
        string(name: 'PARAM_STRING', defaultValue: 'Default Name', description: 'Enter Name')
    }
    stages{
        stage("Build"){
            agent {
                label "slave1"
            }
            steps{
                sh '''
                #!/bin/bash
                sleep 10
                echo $PARAM_STRING
                echo "========executing BUILD ========"
                '''
            }
        }
        stage("Build1"){
            agent any
            steps{
                sh '''
                #!/bin/bash
                sleep 10
                echo "========executing BUILD1 ========"
                '''
            }
        }
        stage("Test"){
            agent any
            steps{
                sh """
                #!/bin/bash
                sleep 10
                echo "========executing TEST ========"
                """
            }
        }
        stage("Test1"){
            agent {
                label "slave2"
            }
            steps{
                script {
                    echo "Hello world"
                    echo "${params.PARAM_STRING}"
                }
            }
        }
    }
}