pipeline{
    agent none
    environment{
        TEST = "This is a test variable"
        TEST1 = "This is a test1 variable"
    }
    
    stages{
        stage("Build"){
            agent {
                label "slave1"
            }
            steps{
                sh '''
                #!/bin/bash
                sleep 10
                echo $TEST $TEST1
                echo "========executing BUILD ========"
                '''
            }
        }
        stage("Build1"){
            agent any
            steps{
                sh '''
                #!/bin/bash
                echo $TEST $TEST1
                sleep 10
                echo "========executing BUILD1 ========"
                '''
            }
        }
        stage("Test"){
            agent any
            steps{
                sh """
                #!/bin/bash
                sleep 10 && echo $TEST $TEST1
                echo "========executing TEST ========"
                """
            }
        }
        stage("Test1"){
            agent any
            steps{
                sh '''
                #!/bin/bash
                sleep 10
                echo "========executing TEST1 ========"
                echo $TEST $TEST1
                '''
            }
        }
    }
}